// This file is auto-generated by gml.
package testy

/*
#cgo pkg-config: Qt5Core Qt5Qml Qt5Quick
#cgo LDFLAGS: -lstdc++
#include <stdlib.h>
#include <stdint.h>
#include <gml_gen.h>

extern void gml_gen_testy_Bridge_dooo_go_slot(void* _goPtr);

static void gml_gen_testy_Bridge_register() {
    gml_gen_testy_Bridge_dooo_cb_register(gml_gen_testy_Bridge_dooo_go_slot);
}
*/
import "C"
import (
    "unsafe"
    "runtime"

	 
	"github.com/desertbit/gml/pointer"
)

//###
//### Bridge
//###

func init() {
    C.gml_gen_testy_Bridge_register()
}

func (_v *Bridge) GMLInit() {
    goPtr := pointer.Save(_v)
    _v.GMLObject_SetPointer(unsafe.Pointer(C.gml_gen_testy_Bridge_new(goPtr)))
    runtime.SetFinalizer(_v, func(_v *Bridge) {
        C.gml_gen_testy_Bridge_free((C.gml_gen_testy_Bridge)(_v.GMLObject_Pointer()))
        pointer.Unref(goPtr)
    })
}

//export gml_gen_testy_Bridge_dooo_go_slot
func gml_gen_testy_Bridge_dooo_go_slot(_goPtr unsafe.Pointer)  {
	_v := (pointer.Restore(_goPtr)).(*Bridge)
    
    _v.dooo()
}

