FROM ubuntu:18.04
MAINTAINER team@desertbit.com

# Install dependencies.
RUN apt-get -y update && \
    apt-get -y install build-essential sudo git wget nano make pkg-config \
        qt5-default qttools5-dev-tools qtdeclarative5-dev && \
    apt-get -y clean

#import common/base