FROM therecipe/qt:windows_64_static

ENV CROSS_TRIPLE="x86_64-w64-mingw32.static"
ENV QT_ROOT="/usr/lib/mxe/usr/$CROSS_TRIPLE/qt5" \
    GOOS=windows \
    GOARCH=amd64

#import common.base

RUN mkdir -p /cross-bin && \
    export MXE_BIN="/usr/lib/mxe/usr/bin" && \
    ln -s "$MXE_BIN/$CROSS_TRIPLE-gcc" /cross-bin/gcc && \
    ln -s "$MXE_BIN/$CROSS_TRIPLE-strip" /cross-bin/strip
ENV PATH="/cross-bin:$PATH"