FROM therecipe/qt:windows_64_static

ENV CROSS_TRIPLE="x86_64-w64-mingw32.static"
ENV QT_ROOT="/usr/lib/mxe/usr/$CROSS_TRIPLE/qt5" \
    GOOS=windows \
    GOARCH=amd64

#import common.base

RUN mkdir -p /cross-bin && \
    for f in /usr/lib/mxe/usr/bin/${CROSS_TRIPLE}-*; do \
        name="$(echo "$f" | sed -e "s|^/usr/lib/mxe/usr/bin/${CROSS_TRIPLE}-||")" ;\
        ln -s "$f" "/cross-bin/${name}" ;\
    done
ENV PATH="/cross-bin:$PATH"
